/*
  Author: Vinod S.R
  Date: 30/06/07 12:10
*/
//  ------------------------------------------------------------------------ //
//                Gooey "see"pp - The ultimate GUI Toolkit                      //
//                    Copyright (c) 2007 tenthstone                            //
//                       <http://www.tenthstone.com/gui/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //


  static int hcount=5;
  /* main menu */
  static char h_menu[20][20]={" Form "," View "," Tools "," Generate "," Help "};
  /* Submenu 1 */
  static char v_menu1[10][20]={" New Form " , " Open Form "," Save Form "," Close Form "," Exit "};
  static int vcount1=5;
  /* Submenu 2 */
 static char v_menu2[10][20]={" Foreground " ," Background "};
 static  int vcount2=2;
    /* Submenu 3 */
 static char v_menu3[10][20]={" Control Browser "};
 static  int vcount3=1;
   /* Submenu 4 */
 static char v_menu4[10][20]={" Generate Code " };
 static  int vcount4=1;
   /* Submenu 5 */
 static char v_menu5[10][20]={" Help " , " About "};
 static  int vcount5=2;


