/*
  Author: Vinod S.R
  Date: 30/06/07 12:10
*/
//  ------------------------------------------------------------------------ //
//                Gooey "see"pp - The ultimate GUI Toolkit                      //
//                    Copyright (c) 2007 tenthstone                            //
//                       <http://www.tenthstone.com/gui/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //



//Window class
#include ".\gui\cwin.h"

//Control Classes
#include ".\gui\button.h"
#include ".\gui\textbox.h"
#include ".\gui\label.h"
#include ".\gui\chkbox.h"
#include ".\gui\option.h"
#include ".\gui\frame.h"
#include ".\gui\line.h"

//Message Box
#include ".\gui\msg_box.h"

// database
#include ".\gui\cdata.h"

//Event handler
#include ".\gui\event.h"

//Definition of class-functions
#include ".\gui\gd_def.h"

#include ".\gui\bttn_def.h"
#include ".\gui\txt_def.h"
#include ".\gui\lab_def.h"
#include ".\gui\cbox_def.h"
#include ".\gui\optn_def.h"
#include ".\gui\frm_def.h"
#include ".\gui\line_def.h"
#include ".\gui\msg_def.h"

#include ".\gui\cwin_def.h"

