/*
  Author: Vinod S.R
  Date: 30/06/07 12:10
*/
//  ------------------------------------------------------------------------ //
//                Gooey "see"pp - The ultimate GUI Toolkit                      //
//                    Copyright (c) 2007 tenthstone                            //
//                       <http://www.tenthstone.com/gui/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //

//To include standard header files;

#if !defined( __STDIO_H )
#include <stdio.h>
#endif

#if !defined( __STDLIB_H )
#include <stdlib.h>
#endif

#if !defined( __CTYPE_H )
#include <ctype.h>
#endif

#if !defined( __DOS_H )
#include <dos.h>
#endif
 
#if !defined( __MATH_H )
#include <math.h>
#endif

#if !defined( __DIR_H )
#include <dir.h>
#endif


#if !defined( __STRING_H )
#include <string.h>
#endif

#if !defined( __FSTREAM_H )
#include <fstream.h>
#endif

#if !defined( __ALLOC_H )
// #include <alloc.h>
#endif

#if !defined( __PROCESS_H )
//#include <process.h>
#endif
 
#if !defined( __IOSTREAM_H )
#include <iostream.h>
#endif

#if !defined( __CONIO_H )
#include <conio.h>
#endif

#if !defined( __GRAPHICS_H )
#include <graphics.h>
#endif
